runtime: custom
service: default
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
network:
  instance_ip_mode: internal
  name: icai-consultants-hack-20042025
  subnetwork_name: icai-consultants-hack-20042025-subnet1
handlers:
- url: /.*
  script: auto
